name: Deploy Flask App to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        KEY: ${{ secrets.EC2_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$KEY" > /tmp/ec2_key.pem
        chmod 600 /tmp/ec2_key.pem
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

        # Copia los archivos al servidor EC2
        scp -i /tmp/ec2_key.pem -r * $USER@$HOST:/home/ubuntu/myapp/

        # Reiniciar la aplicación Flask
        ssh -i /tmp/ec2_key.pem $USER@$HOST << EOF
          cd /home/ubuntu/myapp
          source venv/bin/activate
          pip install -r requirements.txt  # Asegura que las dependencias estén instaladas
          sudo systemctl restart flask-app  # Reinicia el servicio Flask (si lo configuraste con systemd)
        EOF
